name: earthenterprise
version: 5.2.5-714.41
summary: Earth Enterprise is the open source release of Google Earth Enterprise, a geospatial application which 
provides the ability to build and host custom 3D globes and 2D maps.
description: 
  
agrade: stable
confinement: classic

architectures:
  - build-on: amd64

apps:
  earthenterprise:
    command: bin/desktop-launch $SNAP/bin/EarthEnterprise
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"

parts:
  earthenterprise:
    after: [desktop-glib-only]
    plugin: dump
    source:
      - on amd64: https://github.com/google/earthenterprise/archive/$SNAPCRAFT_PROJECT_VERSION/EarthEnterprise_v$SNAPCRAFT_PROJECT_VERSION.tar.gz
      
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2-mesa
      - libflac8
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libasyncns0
      - libogg0
      - libpulse0
      - libsndfile1
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwebp5
    organize:
'EarthEnterprise_v*': 'bin/EarthEnterprise'
