name: earthenterprise
summary: Earth Enterprise is the open source release of Google Earth Enterprise, a geospatial application which 
provides the ability to build and host custom 3D globes and 2D maps.
description: 
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  earthenterprise:
    command: bin/earthenterprise
    plugs:
      - home
      - network
      - removable-media

parts:
  earthenterprise:
    plugin: 
    source: https://github.com/google/earthenterprise.git
    source-type: git
    override-pull: |
      git clone https://github.com/google/earthenterprise.gitsrc/github.com/google/earthenterprise
       cd src/github.com/google/earthenterprise
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/google/earthenterprise
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/google/earthenterprise/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/google/earthenterprise/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/earthenterprise
    build-snaps:
      -
    build-packages:
      - git
      - sed
